# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(X) {
    .Call('_rQESN_test', PACKAGE = 'rQESN', X)
}

fitESN <- function(Xtrain, Ytrain, Xtest, param) {
    .Call('_rQESN_fitESN', PACKAGE = 'rQESN', Xtrain, Ytrain, Xtest, param)
}

